services:

  # Override Jenkins Service
  jenkins:
    container_name: jenkins-blueocean-linux

    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"

    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

    networks:
      - jenkins

  # Override Docker Cloud Service
  docker_proxy:
    command: >
      tcp-listen:2375,fork,reuseaddr
      unix-connect:/var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs: